# Kube Prometheus Stack usando Helm
# Assim posso usar o ServiceMonitor/PodMonitor de maneira mais enxuta
grafana:
  service:
    type: NodePort
    nodePort: 30300

prometheus:
  service:
    type: NodePort
    nodePort: 30090

prometheusOperator:
  enabled: true

alertmanager:
  enabled: false

kubeEtcd:
  enabled: false

kubeControllerManager:
  enabled: false

kubeScheduler:
  enabled: false