apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
data:
  password: cG9zdGdyZXMxMjM= # postgres123 em base64. A senha fica um pouco diferente da default, que é postgres
  datasource: cG9zdGdyZXM6cG9zdGdyZXMxMjNAcG9zdGdyZXMtc2VydmljZS5kZXYuc3ZjLmNsdXN0ZXIubG9jYWw6NTQzMi92b3RhY2FvP3NzbG1vZGU9ZGlzYWJsZQ==
  # postgres:postgres123@postgres-service.dev.svc.cluster.local:5432/votacao?sslmode=disable
