# Este arquivo deve ser aplicado no ambiente local com
# kubectl apply -f
apiVersion: v1
kind: Secret
metadata:
  name: github-sa-token
  namespace: kube-system
  annotations:
    kubernetes.io/service-account.name: github-sa
type: kubernetes.io/service-account-token
