apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: dev
type: Opaque
data:
  password: cG9zdGdyZXMxMjM= # postgres123 em base64. A senha fica um pouco diferente da default, que é postgres
