apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-votacao
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-votacao
  template:
    metadata:
      labels:
        app: backend-votacao
    spec:
      containers:
        - name: backend-votacao
          image: ${BACKEND_IMAGE}
          imagePullPolicy: Always
          ports:
            - name: http-metrics
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dev
spec:
  selector:
    app: backend-votacao
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: backend-votacao
  namespace: dev
  labels:
    release: monitoring
spec:
  selector:
    matchLabels:
      app: backend-votacao
  podMetricsEndpoints:
    - port: "http-metrics"
      path: /metrics
      interval: 15s
      