apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-votacao
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-votacao
  template:
    metadata:
      labels:
        app: backend-votacao
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "5000"
        prometheus.io/path: "/metrics"
    spec:
      containers:
        - name: backend-votacao
          image: ${BACKEND_IMAGE}
          imagePullPolicy: Always
          ports:
            - name: http 
              containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: dev
spec:
  selector:
    app: backend-votacao
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: backend-votacao
  namespace: monitoring  # Namespace onde o Prometheus está
spec:
  selector:
    matchLabels:
      app: backend-votacao
  namespaceSelector:
    matchNames:
      - dev
  podMetricsEndpoints:
    - port: http
      path: /metrics
      interval: 15s
