apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-votacao
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-votacao
  template:
    metadata:
      labels:
        app: frontend-votacao
    spec:
      containers:
        - name: frontend-votacao
          image: annagtaraujo/frontend-votacao:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
spec:
  selector:
    app: frontend-votacao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
