apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-votacao
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-votacao
  template:
    metadata:
      labels:
        app: frontend-votacao
    spec:
      containers:
        - name: frontend-votacao
          image: ${FRONTEND_IMAGE}
          imagePullPolicy: Always
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: dev
spec:
  selector:
    app: frontend-votacao
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort
