apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis-exporter
  namespace: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis-exporter
  template:
    metadata:
      labels:
        app: redis-exporter
    spec:
      containers:
        - name: redis-exporter
          image: oliver006/redis_exporter:v1.55.0
          args:
            - "--redis.addr=redis://redis-service.dev.svc.cluster.local:6379"
          ports:
            - containerPort: 9121
---
apiVersion: v1
kind: Service
metadata:
  name: redis-exporter
  namespace: dev
  labels:
    app: redis-exporter
spec:
  selector:
    app: redis-exporter
  ports:
    - name: http
      port: 9121
      targetPort: 9121
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: redis-exporter
  namespace: dev
  labels:
    release: monitoring  # Para que o Prometheus encontre o Monitor
spec:
  selector:
    matchLabels:
      app: redis-exporter
  endpoints:
    - port: http
      interval: 15s
