name: Deploy Workload Test with Grafana k6

on:
  workflow_run:
    workflows: ["Deploy Monitoring Stack using Helm"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Decode kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig.yaml

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Add Helm repo
      run: |
        helm repo add grafana https://grafana.github.io/helm-charts
        helm repo update

    - name: Install Grafana k6
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
      run: |
        helm install k6-operator grafana/k6-operator --namespace monitoring --wait --timeout 5m

    - name: Apply workload test config
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
      run: |
        kubectl apply -f k8s/monitoring/grafana-k6/votacao-load-test-configmap.yaml
        kubectl delete testrun.v1alpha1.k6.io votacao-load-test --namespace monitoring --ignore-not-found
        kubectl apply -f k8s/monitoring/grafana-k6/votacao-load-test.yaml