name: Deploy Monitoring Stack using Helm

on:
  workflow_run:
    workflows: ["Build and Push Docker Images"]
    branches: [main]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Decode kubeconfig
      run: |
        echo "${{ secrets.KUBECONFIG_B64 }}" | base64 -d > kubeconfig.yaml

    - name: Set up Helm
      uses: azure/setup-helm@v3

    - name: Add Helm repo
      run: |
        helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
        helm repo update

    - name: Cleanup Helm release if locked
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
      run: |
        if helm status monitoring -n monitoring > /dev/null 2>&1; then
          STATUS=$(helm status monitoring -n monitoring -o json | jq -r .info.status)
          if [[ "$STATUS" == "pending-upgrade" || "$STATUS" == "pending-install" ]]; then
            echo "Release in $STATUS state. Uninstalling..."
            helm uninstall monitoring -n monitoring
          fi
        fi
        
    - name: Install kube-prometheus-stack
      env:
        KUBECONFIG: ${{ github.workspace }}/kubeconfig.yaml
      run: |
        helm upgrade --install monitoring prometheus-community/kube-prometheus-stack \
          --namespace monitoring \
          --create-namespace \
          --wait \
          --timeout 5m \
          -f k8s/monitoring/kube-prometheus-stack/values.yaml
