apiVersion: k6.io/v1alpha1
kind: TestRun
metadata:
  name: votacao-load-test
  namespace: monitoring
spec:
  parallelism: 1
  script:
    source:
      type: ConfigMap
      name: votacao-k6-script
      file: script.js
